name: Pull request

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  tests:
    name: Test
    uses: swiftlang/github-workflows/.github/workflows/swift_package_test.yml@main
    with:
      linux_os_versions: '["jammy", "focal"]'
      enable_macos_checks: false
      macos_xcode_versions: '["16.3"]'

  soundness:
    name: Soundness
    uses: swiftlang/github-workflows/.github/workflows/soundness.yml@main
    with:
      license_header_check_project_name: "Swift.org"
      # https://github.com/apple/swift-system/issues/224
      docs_check_enabled: false
      unacceptable_language_check_enabled: false
      license_header_check_enabled: false
      format_check_enabled: false
      python_lint_check_enabled: false
